
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RoastProfile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RoastProfile
 * 
 */
export type RoastProfileModel = runtime.Types.Result.DefaultSelection<Prisma.$RoastProfilePayload>

export type AggregateRoastProfile = {
  _count: RoastProfileCountAggregateOutputType | null
  _avg: RoastProfileAvgAggregateOutputType | null
  _sum: RoastProfileSumAggregateOutputType | null
  _min: RoastProfileMinAggregateOutputType | null
  _max: RoastProfileMaxAggregateOutputType | null
}

export type RoastProfileAvgAggregateOutputType = {
  weightIn: number | null
  weightOut: number | null
  weightLossPct: number | null
  totalRoastTime: number | null
  developmentTime: number | null
  devTimeRatio: number | null
}

export type RoastProfileSumAggregateOutputType = {
  weightIn: number | null
  weightOut: number | null
  weightLossPct: number | null
  totalRoastTime: number | null
  developmentTime: number | null
  devTimeRatio: number | null
}

export type RoastProfileMinAggregateOutputType = {
  id: string | null
  batchId: string | null
  date: Date | null
  beanType: string | null
  weightIn: number | null
  weightOut: number | null
  weightLossPct: number | null
  totalRoastTime: number | null
  developmentTime: number | null
  devTimeRatio: number | null
  notes: string | null
  inventoryItemId: string | null
}

export type RoastProfileMaxAggregateOutputType = {
  id: string | null
  batchId: string | null
  date: Date | null
  beanType: string | null
  weightIn: number | null
  weightOut: number | null
  weightLossPct: number | null
  totalRoastTime: number | null
  developmentTime: number | null
  devTimeRatio: number | null
  notes: string | null
  inventoryItemId: string | null
}

export type RoastProfileCountAggregateOutputType = {
  id: number
  batchId: number
  date: number
  beanType: number
  weightIn: number
  weightOut: number
  weightLossPct: number
  totalRoastTime: number
  developmentTime: number
  devTimeRatio: number
  roastCurveData: number
  notes: number
  inventoryItemId: number
  _all: number
}


export type RoastProfileAvgAggregateInputType = {
  weightIn?: true
  weightOut?: true
  weightLossPct?: true
  totalRoastTime?: true
  developmentTime?: true
  devTimeRatio?: true
}

export type RoastProfileSumAggregateInputType = {
  weightIn?: true
  weightOut?: true
  weightLossPct?: true
  totalRoastTime?: true
  developmentTime?: true
  devTimeRatio?: true
}

export type RoastProfileMinAggregateInputType = {
  id?: true
  batchId?: true
  date?: true
  beanType?: true
  weightIn?: true
  weightOut?: true
  weightLossPct?: true
  totalRoastTime?: true
  developmentTime?: true
  devTimeRatio?: true
  notes?: true
  inventoryItemId?: true
}

export type RoastProfileMaxAggregateInputType = {
  id?: true
  batchId?: true
  date?: true
  beanType?: true
  weightIn?: true
  weightOut?: true
  weightLossPct?: true
  totalRoastTime?: true
  developmentTime?: true
  devTimeRatio?: true
  notes?: true
  inventoryItemId?: true
}

export type RoastProfileCountAggregateInputType = {
  id?: true
  batchId?: true
  date?: true
  beanType?: true
  weightIn?: true
  weightOut?: true
  weightLossPct?: true
  totalRoastTime?: true
  developmentTime?: true
  devTimeRatio?: true
  roastCurveData?: true
  notes?: true
  inventoryItemId?: true
  _all?: true
}

export type RoastProfileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RoastProfile to aggregate.
   */
  where?: Prisma.RoastProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoastProfiles to fetch.
   */
  orderBy?: Prisma.RoastProfileOrderByWithRelationInput | Prisma.RoastProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RoastProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoastProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoastProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RoastProfiles
  **/
  _count?: true | RoastProfileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RoastProfileAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RoastProfileSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RoastProfileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RoastProfileMaxAggregateInputType
}

export type GetRoastProfileAggregateType<T extends RoastProfileAggregateArgs> = {
      [P in keyof T & keyof AggregateRoastProfile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRoastProfile[P]>
    : Prisma.GetScalarType<T[P], AggregateRoastProfile[P]>
}




export type RoastProfileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RoastProfileWhereInput
  orderBy?: Prisma.RoastProfileOrderByWithAggregationInput | Prisma.RoastProfileOrderByWithAggregationInput[]
  by: Prisma.RoastProfileScalarFieldEnum[] | Prisma.RoastProfileScalarFieldEnum
  having?: Prisma.RoastProfileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RoastProfileCountAggregateInputType | true
  _avg?: RoastProfileAvgAggregateInputType
  _sum?: RoastProfileSumAggregateInputType
  _min?: RoastProfileMinAggregateInputType
  _max?: RoastProfileMaxAggregateInputType
}

export type RoastProfileGroupByOutputType = {
  id: string
  batchId: string
  date: Date
  beanType: string
  weightIn: number
  weightOut: number
  weightLossPct: number | null
  totalRoastTime: number | null
  developmentTime: number | null
  devTimeRatio: number | null
  roastCurveData: runtime.JsonValue | null
  notes: string | null
  inventoryItemId: string | null
  _count: RoastProfileCountAggregateOutputType | null
  _avg: RoastProfileAvgAggregateOutputType | null
  _sum: RoastProfileSumAggregateOutputType | null
  _min: RoastProfileMinAggregateOutputType | null
  _max: RoastProfileMaxAggregateOutputType | null
}

type GetRoastProfileGroupByPayload<T extends RoastProfileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RoastProfileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RoastProfileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RoastProfileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RoastProfileGroupByOutputType[P]>
      }
    >
  >



export type RoastProfileWhereInput = {
  AND?: Prisma.RoastProfileWhereInput | Prisma.RoastProfileWhereInput[]
  OR?: Prisma.RoastProfileWhereInput[]
  NOT?: Prisma.RoastProfileWhereInput | Prisma.RoastProfileWhereInput[]
  id?: Prisma.StringFilter<"RoastProfile"> | string
  batchId?: Prisma.StringFilter<"RoastProfile"> | string
  date?: Prisma.DateTimeFilter<"RoastProfile"> | Date | string
  beanType?: Prisma.StringFilter<"RoastProfile"> | string
  weightIn?: Prisma.FloatFilter<"RoastProfile"> | number
  weightOut?: Prisma.FloatFilter<"RoastProfile"> | number
  weightLossPct?: Prisma.FloatNullableFilter<"RoastProfile"> | number | null
  totalRoastTime?: Prisma.IntNullableFilter<"RoastProfile"> | number | null
  developmentTime?: Prisma.IntNullableFilter<"RoastProfile"> | number | null
  devTimeRatio?: Prisma.FloatNullableFilter<"RoastProfile"> | number | null
  roastCurveData?: Prisma.JsonNullableFilter<"RoastProfile">
  notes?: Prisma.StringNullableFilter<"RoastProfile"> | string | null
  inventoryItemId?: Prisma.StringNullableFilter<"RoastProfile"> | string | null
  inventoryItem?: Prisma.XOR<Prisma.InventoryItemNullableScalarRelationFilter, Prisma.InventoryItemWhereInput> | null
}

export type RoastProfileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  beanType?: Prisma.SortOrder
  weightIn?: Prisma.SortOrder
  weightOut?: Prisma.SortOrder
  weightLossPct?: Prisma.SortOrderInput | Prisma.SortOrder
  totalRoastTime?: Prisma.SortOrderInput | Prisma.SortOrder
  developmentTime?: Prisma.SortOrderInput | Prisma.SortOrder
  devTimeRatio?: Prisma.SortOrderInput | Prisma.SortOrder
  roastCurveData?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  inventoryItemId?: Prisma.SortOrderInput | Prisma.SortOrder
  inventoryItem?: Prisma.InventoryItemOrderByWithRelationInput
}

export type RoastProfileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  batchId?: string
  AND?: Prisma.RoastProfileWhereInput | Prisma.RoastProfileWhereInput[]
  OR?: Prisma.RoastProfileWhereInput[]
  NOT?: Prisma.RoastProfileWhereInput | Prisma.RoastProfileWhereInput[]
  date?: Prisma.DateTimeFilter<"RoastProfile"> | Date | string
  beanType?: Prisma.StringFilter<"RoastProfile"> | string
  weightIn?: Prisma.FloatFilter<"RoastProfile"> | number
  weightOut?: Prisma.FloatFilter<"RoastProfile"> | number
  weightLossPct?: Prisma.FloatNullableFilter<"RoastProfile"> | number | null
  totalRoastTime?: Prisma.IntNullableFilter<"RoastProfile"> | number | null
  developmentTime?: Prisma.IntNullableFilter<"RoastProfile"> | number | null
  devTimeRatio?: Prisma.FloatNullableFilter<"RoastProfile"> | number | null
  roastCurveData?: Prisma.JsonNullableFilter<"RoastProfile">
  notes?: Prisma.StringNullableFilter<"RoastProfile"> | string | null
  inventoryItemId?: Prisma.StringNullableFilter<"RoastProfile"> | string | null
  inventoryItem?: Prisma.XOR<Prisma.InventoryItemNullableScalarRelationFilter, Prisma.InventoryItemWhereInput> | null
}, "id" | "batchId">

export type RoastProfileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  beanType?: Prisma.SortOrder
  weightIn?: Prisma.SortOrder
  weightOut?: Prisma.SortOrder
  weightLossPct?: Prisma.SortOrderInput | Prisma.SortOrder
  totalRoastTime?: Prisma.SortOrderInput | Prisma.SortOrder
  developmentTime?: Prisma.SortOrderInput | Prisma.SortOrder
  devTimeRatio?: Prisma.SortOrderInput | Prisma.SortOrder
  roastCurveData?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  inventoryItemId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.RoastProfileCountOrderByAggregateInput
  _avg?: Prisma.RoastProfileAvgOrderByAggregateInput
  _max?: Prisma.RoastProfileMaxOrderByAggregateInput
  _min?: Prisma.RoastProfileMinOrderByAggregateInput
  _sum?: Prisma.RoastProfileSumOrderByAggregateInput
}

export type RoastProfileScalarWhereWithAggregatesInput = {
  AND?: Prisma.RoastProfileScalarWhereWithAggregatesInput | Prisma.RoastProfileScalarWhereWithAggregatesInput[]
  OR?: Prisma.RoastProfileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RoastProfileScalarWhereWithAggregatesInput | Prisma.RoastProfileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RoastProfile"> | string
  batchId?: Prisma.StringWithAggregatesFilter<"RoastProfile"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"RoastProfile"> | Date | string
  beanType?: Prisma.StringWithAggregatesFilter<"RoastProfile"> | string
  weightIn?: Prisma.FloatWithAggregatesFilter<"RoastProfile"> | number
  weightOut?: Prisma.FloatWithAggregatesFilter<"RoastProfile"> | number
  weightLossPct?: Prisma.FloatNullableWithAggregatesFilter<"RoastProfile"> | number | null
  totalRoastTime?: Prisma.IntNullableWithAggregatesFilter<"RoastProfile"> | number | null
  developmentTime?: Prisma.IntNullableWithAggregatesFilter<"RoastProfile"> | number | null
  devTimeRatio?: Prisma.FloatNullableWithAggregatesFilter<"RoastProfile"> | number | null
  roastCurveData?: Prisma.JsonNullableWithAggregatesFilter<"RoastProfile">
  notes?: Prisma.StringNullableWithAggregatesFilter<"RoastProfile"> | string | null
  inventoryItemId?: Prisma.StringNullableWithAggregatesFilter<"RoastProfile"> | string | null
}

export type RoastProfileCreateInput = {
  id?: string
  batchId: string
  date?: Date | string
  beanType: string
  weightIn: number
  weightOut: number
  weightLossPct?: number | null
  totalRoastTime?: number | null
  developmentTime?: number | null
  devTimeRatio?: number | null
  roastCurveData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notes?: string | null
  inventoryItem?: Prisma.InventoryItemCreateNestedOneWithoutRoastsInput
}

export type RoastProfileUncheckedCreateInput = {
  id?: string
  batchId: string
  date?: Date | string
  beanType: string
  weightIn: number
  weightOut: number
  weightLossPct?: number | null
  totalRoastTime?: number | null
  developmentTime?: number | null
  devTimeRatio?: number | null
  roastCurveData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notes?: string | null
  inventoryItemId?: string | null
}

export type RoastProfileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  beanType?: Prisma.StringFieldUpdateOperationsInput | string
  weightIn?: Prisma.FloatFieldUpdateOperationsInput | number
  weightOut?: Prisma.FloatFieldUpdateOperationsInput | number
  weightLossPct?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  totalRoastTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  developmentTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  devTimeRatio?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  roastCurveData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  inventoryItem?: Prisma.InventoryItemUpdateOneWithoutRoastsNestedInput
}

export type RoastProfileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  beanType?: Prisma.StringFieldUpdateOperationsInput | string
  weightIn?: Prisma.FloatFieldUpdateOperationsInput | number
  weightOut?: Prisma.FloatFieldUpdateOperationsInput | number
  weightLossPct?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  totalRoastTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  developmentTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  devTimeRatio?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  roastCurveData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  inventoryItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RoastProfileCreateManyInput = {
  id?: string
  batchId: string
  date?: Date | string
  beanType: string
  weightIn: number
  weightOut: number
  weightLossPct?: number | null
  totalRoastTime?: number | null
  developmentTime?: number | null
  devTimeRatio?: number | null
  roastCurveData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notes?: string | null
  inventoryItemId?: string | null
}

export type RoastProfileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  beanType?: Prisma.StringFieldUpdateOperationsInput | string
  weightIn?: Prisma.FloatFieldUpdateOperationsInput | number
  weightOut?: Prisma.FloatFieldUpdateOperationsInput | number
  weightLossPct?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  totalRoastTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  developmentTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  devTimeRatio?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  roastCurveData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RoastProfileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  beanType?: Prisma.StringFieldUpdateOperationsInput | string
  weightIn?: Prisma.FloatFieldUpdateOperationsInput | number
  weightOut?: Prisma.FloatFieldUpdateOperationsInput | number
  weightLossPct?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  totalRoastTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  developmentTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  devTimeRatio?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  roastCurveData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  inventoryItemId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RoastProfileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  beanType?: Prisma.SortOrder
  weightIn?: Prisma.SortOrder
  weightOut?: Prisma.SortOrder
  weightLossPct?: Prisma.SortOrder
  totalRoastTime?: Prisma.SortOrder
  developmentTime?: Prisma.SortOrder
  devTimeRatio?: Prisma.SortOrder
  roastCurveData?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  inventoryItemId?: Prisma.SortOrder
}

export type RoastProfileAvgOrderByAggregateInput = {
  weightIn?: Prisma.SortOrder
  weightOut?: Prisma.SortOrder
  weightLossPct?: Prisma.SortOrder
  totalRoastTime?: Prisma.SortOrder
  developmentTime?: Prisma.SortOrder
  devTimeRatio?: Prisma.SortOrder
}

export type RoastProfileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  beanType?: Prisma.SortOrder
  weightIn?: Prisma.SortOrder
  weightOut?: Prisma.SortOrder
  weightLossPct?: Prisma.SortOrder
  totalRoastTime?: Prisma.SortOrder
  developmentTime?: Prisma.SortOrder
  devTimeRatio?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  inventoryItemId?: Prisma.SortOrder
}

export type RoastProfileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  batchId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  beanType?: Prisma.SortOrder
  weightIn?: Prisma.SortOrder
  weightOut?: Prisma.SortOrder
  weightLossPct?: Prisma.SortOrder
  totalRoastTime?: Prisma.SortOrder
  developmentTime?: Prisma.SortOrder
  devTimeRatio?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  inventoryItemId?: Prisma.SortOrder
}

export type RoastProfileSumOrderByAggregateInput = {
  weightIn?: Prisma.SortOrder
  weightOut?: Prisma.SortOrder
  weightLossPct?: Prisma.SortOrder
  totalRoastTime?: Prisma.SortOrder
  developmentTime?: Prisma.SortOrder
  devTimeRatio?: Prisma.SortOrder
}

export type RoastProfileListRelationFilter = {
  every?: Prisma.RoastProfileWhereInput
  some?: Prisma.RoastProfileWhereInput
  none?: Prisma.RoastProfileWhereInput
}

export type RoastProfileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type RoastProfileCreateNestedManyWithoutInventoryItemInput = {
  create?: Prisma.XOR<Prisma.RoastProfileCreateWithoutInventoryItemInput, Prisma.RoastProfileUncheckedCreateWithoutInventoryItemInput> | Prisma.RoastProfileCreateWithoutInventoryItemInput[] | Prisma.RoastProfileUncheckedCreateWithoutInventoryItemInput[]
  connectOrCreate?: Prisma.RoastProfileCreateOrConnectWithoutInventoryItemInput | Prisma.RoastProfileCreateOrConnectWithoutInventoryItemInput[]
  createMany?: Prisma.RoastProfileCreateManyInventoryItemInputEnvelope
  connect?: Prisma.RoastProfileWhereUniqueInput | Prisma.RoastProfileWhereUniqueInput[]
}

export type RoastProfileUncheckedCreateNestedManyWithoutInventoryItemInput = {
  create?: Prisma.XOR<Prisma.RoastProfileCreateWithoutInventoryItemInput, Prisma.RoastProfileUncheckedCreateWithoutInventoryItemInput> | Prisma.RoastProfileCreateWithoutInventoryItemInput[] | Prisma.RoastProfileUncheckedCreateWithoutInventoryItemInput[]
  connectOrCreate?: Prisma.RoastProfileCreateOrConnectWithoutInventoryItemInput | Prisma.RoastProfileCreateOrConnectWithoutInventoryItemInput[]
  createMany?: Prisma.RoastProfileCreateManyInventoryItemInputEnvelope
  connect?: Prisma.RoastProfileWhereUniqueInput | Prisma.RoastProfileWhereUniqueInput[]
}

export type RoastProfileUpdateManyWithoutInventoryItemNestedInput = {
  create?: Prisma.XOR<Prisma.RoastProfileCreateWithoutInventoryItemInput, Prisma.RoastProfileUncheckedCreateWithoutInventoryItemInput> | Prisma.RoastProfileCreateWithoutInventoryItemInput[] | Prisma.RoastProfileUncheckedCreateWithoutInventoryItemInput[]
  connectOrCreate?: Prisma.RoastProfileCreateOrConnectWithoutInventoryItemInput | Prisma.RoastProfileCreateOrConnectWithoutInventoryItemInput[]
  upsert?: Prisma.RoastProfileUpsertWithWhereUniqueWithoutInventoryItemInput | Prisma.RoastProfileUpsertWithWhereUniqueWithoutInventoryItemInput[]
  createMany?: Prisma.RoastProfileCreateManyInventoryItemInputEnvelope
  set?: Prisma.RoastProfileWhereUniqueInput | Prisma.RoastProfileWhereUniqueInput[]
  disconnect?: Prisma.RoastProfileWhereUniqueInput | Prisma.RoastProfileWhereUniqueInput[]
  delete?: Prisma.RoastProfileWhereUniqueInput | Prisma.RoastProfileWhereUniqueInput[]
  connect?: Prisma.RoastProfileWhereUniqueInput | Prisma.RoastProfileWhereUniqueInput[]
  update?: Prisma.RoastProfileUpdateWithWhereUniqueWithoutInventoryItemInput | Prisma.RoastProfileUpdateWithWhereUniqueWithoutInventoryItemInput[]
  updateMany?: Prisma.RoastProfileUpdateManyWithWhereWithoutInventoryItemInput | Prisma.RoastProfileUpdateManyWithWhereWithoutInventoryItemInput[]
  deleteMany?: Prisma.RoastProfileScalarWhereInput | Prisma.RoastProfileScalarWhereInput[]
}

export type RoastProfileUncheckedUpdateManyWithoutInventoryItemNestedInput = {
  create?: Prisma.XOR<Prisma.RoastProfileCreateWithoutInventoryItemInput, Prisma.RoastProfileUncheckedCreateWithoutInventoryItemInput> | Prisma.RoastProfileCreateWithoutInventoryItemInput[] | Prisma.RoastProfileUncheckedCreateWithoutInventoryItemInput[]
  connectOrCreate?: Prisma.RoastProfileCreateOrConnectWithoutInventoryItemInput | Prisma.RoastProfileCreateOrConnectWithoutInventoryItemInput[]
  upsert?: Prisma.RoastProfileUpsertWithWhereUniqueWithoutInventoryItemInput | Prisma.RoastProfileUpsertWithWhereUniqueWithoutInventoryItemInput[]
  createMany?: Prisma.RoastProfileCreateManyInventoryItemInputEnvelope
  set?: Prisma.RoastProfileWhereUniqueInput | Prisma.RoastProfileWhereUniqueInput[]
  disconnect?: Prisma.RoastProfileWhereUniqueInput | Prisma.RoastProfileWhereUniqueInput[]
  delete?: Prisma.RoastProfileWhereUniqueInput | Prisma.RoastProfileWhereUniqueInput[]
  connect?: Prisma.RoastProfileWhereUniqueInput | Prisma.RoastProfileWhereUniqueInput[]
  update?: Prisma.RoastProfileUpdateWithWhereUniqueWithoutInventoryItemInput | Prisma.RoastProfileUpdateWithWhereUniqueWithoutInventoryItemInput[]
  updateMany?: Prisma.RoastProfileUpdateManyWithWhereWithoutInventoryItemInput | Prisma.RoastProfileUpdateManyWithWhereWithoutInventoryItemInput[]
  deleteMany?: Prisma.RoastProfileScalarWhereInput | Prisma.RoastProfileScalarWhereInput[]
}

export type RoastProfileCreateWithoutInventoryItemInput = {
  id?: string
  batchId: string
  date?: Date | string
  beanType: string
  weightIn: number
  weightOut: number
  weightLossPct?: number | null
  totalRoastTime?: number | null
  developmentTime?: number | null
  devTimeRatio?: number | null
  roastCurveData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notes?: string | null
}

export type RoastProfileUncheckedCreateWithoutInventoryItemInput = {
  id?: string
  batchId: string
  date?: Date | string
  beanType: string
  weightIn: number
  weightOut: number
  weightLossPct?: number | null
  totalRoastTime?: number | null
  developmentTime?: number | null
  devTimeRatio?: number | null
  roastCurveData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notes?: string | null
}

export type RoastProfileCreateOrConnectWithoutInventoryItemInput = {
  where: Prisma.RoastProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.RoastProfileCreateWithoutInventoryItemInput, Prisma.RoastProfileUncheckedCreateWithoutInventoryItemInput>
}

export type RoastProfileCreateManyInventoryItemInputEnvelope = {
  data: Prisma.RoastProfileCreateManyInventoryItemInput | Prisma.RoastProfileCreateManyInventoryItemInput[]
  skipDuplicates?: boolean
}

export type RoastProfileUpsertWithWhereUniqueWithoutInventoryItemInput = {
  where: Prisma.RoastProfileWhereUniqueInput
  update: Prisma.XOR<Prisma.RoastProfileUpdateWithoutInventoryItemInput, Prisma.RoastProfileUncheckedUpdateWithoutInventoryItemInput>
  create: Prisma.XOR<Prisma.RoastProfileCreateWithoutInventoryItemInput, Prisma.RoastProfileUncheckedCreateWithoutInventoryItemInput>
}

export type RoastProfileUpdateWithWhereUniqueWithoutInventoryItemInput = {
  where: Prisma.RoastProfileWhereUniqueInput
  data: Prisma.XOR<Prisma.RoastProfileUpdateWithoutInventoryItemInput, Prisma.RoastProfileUncheckedUpdateWithoutInventoryItemInput>
}

export type RoastProfileUpdateManyWithWhereWithoutInventoryItemInput = {
  where: Prisma.RoastProfileScalarWhereInput
  data: Prisma.XOR<Prisma.RoastProfileUpdateManyMutationInput, Prisma.RoastProfileUncheckedUpdateManyWithoutInventoryItemInput>
}

export type RoastProfileScalarWhereInput = {
  AND?: Prisma.RoastProfileScalarWhereInput | Prisma.RoastProfileScalarWhereInput[]
  OR?: Prisma.RoastProfileScalarWhereInput[]
  NOT?: Prisma.RoastProfileScalarWhereInput | Prisma.RoastProfileScalarWhereInput[]
  id?: Prisma.StringFilter<"RoastProfile"> | string
  batchId?: Prisma.StringFilter<"RoastProfile"> | string
  date?: Prisma.DateTimeFilter<"RoastProfile"> | Date | string
  beanType?: Prisma.StringFilter<"RoastProfile"> | string
  weightIn?: Prisma.FloatFilter<"RoastProfile"> | number
  weightOut?: Prisma.FloatFilter<"RoastProfile"> | number
  weightLossPct?: Prisma.FloatNullableFilter<"RoastProfile"> | number | null
  totalRoastTime?: Prisma.IntNullableFilter<"RoastProfile"> | number | null
  developmentTime?: Prisma.IntNullableFilter<"RoastProfile"> | number | null
  devTimeRatio?: Prisma.FloatNullableFilter<"RoastProfile"> | number | null
  roastCurveData?: Prisma.JsonNullableFilter<"RoastProfile">
  notes?: Prisma.StringNullableFilter<"RoastProfile"> | string | null
  inventoryItemId?: Prisma.StringNullableFilter<"RoastProfile"> | string | null
}

export type RoastProfileCreateManyInventoryItemInput = {
  id?: string
  batchId: string
  date?: Date | string
  beanType: string
  weightIn: number
  weightOut: number
  weightLossPct?: number | null
  totalRoastTime?: number | null
  developmentTime?: number | null
  devTimeRatio?: number | null
  roastCurveData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notes?: string | null
}

export type RoastProfileUpdateWithoutInventoryItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  beanType?: Prisma.StringFieldUpdateOperationsInput | string
  weightIn?: Prisma.FloatFieldUpdateOperationsInput | number
  weightOut?: Prisma.FloatFieldUpdateOperationsInput | number
  weightLossPct?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  totalRoastTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  developmentTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  devTimeRatio?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  roastCurveData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RoastProfileUncheckedUpdateWithoutInventoryItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  beanType?: Prisma.StringFieldUpdateOperationsInput | string
  weightIn?: Prisma.FloatFieldUpdateOperationsInput | number
  weightOut?: Prisma.FloatFieldUpdateOperationsInput | number
  weightLossPct?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  totalRoastTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  developmentTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  devTimeRatio?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  roastCurveData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RoastProfileUncheckedUpdateManyWithoutInventoryItemInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  batchId?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  beanType?: Prisma.StringFieldUpdateOperationsInput | string
  weightIn?: Prisma.FloatFieldUpdateOperationsInput | number
  weightOut?: Prisma.FloatFieldUpdateOperationsInput | number
  weightLossPct?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  totalRoastTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  developmentTime?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  devTimeRatio?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  roastCurveData?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type RoastProfileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  batchId?: boolean
  date?: boolean
  beanType?: boolean
  weightIn?: boolean
  weightOut?: boolean
  weightLossPct?: boolean
  totalRoastTime?: boolean
  developmentTime?: boolean
  devTimeRatio?: boolean
  roastCurveData?: boolean
  notes?: boolean
  inventoryItemId?: boolean
  inventoryItem?: boolean | Prisma.RoastProfile$inventoryItemArgs<ExtArgs>
}, ExtArgs["result"]["roastProfile"]>

export type RoastProfileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  batchId?: boolean
  date?: boolean
  beanType?: boolean
  weightIn?: boolean
  weightOut?: boolean
  weightLossPct?: boolean
  totalRoastTime?: boolean
  developmentTime?: boolean
  devTimeRatio?: boolean
  roastCurveData?: boolean
  notes?: boolean
  inventoryItemId?: boolean
  inventoryItem?: boolean | Prisma.RoastProfile$inventoryItemArgs<ExtArgs>
}, ExtArgs["result"]["roastProfile"]>

export type RoastProfileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  batchId?: boolean
  date?: boolean
  beanType?: boolean
  weightIn?: boolean
  weightOut?: boolean
  weightLossPct?: boolean
  totalRoastTime?: boolean
  developmentTime?: boolean
  devTimeRatio?: boolean
  roastCurveData?: boolean
  notes?: boolean
  inventoryItemId?: boolean
  inventoryItem?: boolean | Prisma.RoastProfile$inventoryItemArgs<ExtArgs>
}, ExtArgs["result"]["roastProfile"]>

export type RoastProfileSelectScalar = {
  id?: boolean
  batchId?: boolean
  date?: boolean
  beanType?: boolean
  weightIn?: boolean
  weightOut?: boolean
  weightLossPct?: boolean
  totalRoastTime?: boolean
  developmentTime?: boolean
  devTimeRatio?: boolean
  roastCurveData?: boolean
  notes?: boolean
  inventoryItemId?: boolean
}

export type RoastProfileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "batchId" | "date" | "beanType" | "weightIn" | "weightOut" | "weightLossPct" | "totalRoastTime" | "developmentTime" | "devTimeRatio" | "roastCurveData" | "notes" | "inventoryItemId", ExtArgs["result"]["roastProfile"]>
export type RoastProfileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  inventoryItem?: boolean | Prisma.RoastProfile$inventoryItemArgs<ExtArgs>
}
export type RoastProfileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  inventoryItem?: boolean | Prisma.RoastProfile$inventoryItemArgs<ExtArgs>
}
export type RoastProfileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  inventoryItem?: boolean | Prisma.RoastProfile$inventoryItemArgs<ExtArgs>
}

export type $RoastProfilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RoastProfile"
  objects: {
    inventoryItem: Prisma.$InventoryItemPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    batchId: string
    date: Date
    beanType: string
    weightIn: number
    weightOut: number
    weightLossPct: number | null
    totalRoastTime: number | null
    developmentTime: number | null
    devTimeRatio: number | null
    roastCurveData: runtime.JsonValue | null
    notes: string | null
    inventoryItemId: string | null
  }, ExtArgs["result"]["roastProfile"]>
  composites: {}
}

export type RoastProfileGetPayload<S extends boolean | null | undefined | RoastProfileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RoastProfilePayload, S>

export type RoastProfileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RoastProfileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RoastProfileCountAggregateInputType | true
  }

export interface RoastProfileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RoastProfile'], meta: { name: 'RoastProfile' } }
  /**
   * Find zero or one RoastProfile that matches the filter.
   * @param {RoastProfileFindUniqueArgs} args - Arguments to find a RoastProfile
   * @example
   * // Get one RoastProfile
   * const roastProfile = await prisma.roastProfile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RoastProfileFindUniqueArgs>(args: Prisma.SelectSubset<T, RoastProfileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RoastProfileClient<runtime.Types.Result.GetResult<Prisma.$RoastProfilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RoastProfile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RoastProfileFindUniqueOrThrowArgs} args - Arguments to find a RoastProfile
   * @example
   * // Get one RoastProfile
   * const roastProfile = await prisma.roastProfile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RoastProfileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RoastProfileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RoastProfileClient<runtime.Types.Result.GetResult<Prisma.$RoastProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RoastProfile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoastProfileFindFirstArgs} args - Arguments to find a RoastProfile
   * @example
   * // Get one RoastProfile
   * const roastProfile = await prisma.roastProfile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RoastProfileFindFirstArgs>(args?: Prisma.SelectSubset<T, RoastProfileFindFirstArgs<ExtArgs>>): Prisma.Prisma__RoastProfileClient<runtime.Types.Result.GetResult<Prisma.$RoastProfilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RoastProfile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoastProfileFindFirstOrThrowArgs} args - Arguments to find a RoastProfile
   * @example
   * // Get one RoastProfile
   * const roastProfile = await prisma.roastProfile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RoastProfileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RoastProfileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RoastProfileClient<runtime.Types.Result.GetResult<Prisma.$RoastProfilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RoastProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoastProfileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RoastProfiles
   * const roastProfiles = await prisma.roastProfile.findMany()
   * 
   * // Get first 10 RoastProfiles
   * const roastProfiles = await prisma.roastProfile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const roastProfileWithIdOnly = await prisma.roastProfile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RoastProfileFindManyArgs>(args?: Prisma.SelectSubset<T, RoastProfileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoastProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RoastProfile.
   * @param {RoastProfileCreateArgs} args - Arguments to create a RoastProfile.
   * @example
   * // Create one RoastProfile
   * const RoastProfile = await prisma.roastProfile.create({
   *   data: {
   *     // ... data to create a RoastProfile
   *   }
   * })
   * 
   */
  create<T extends RoastProfileCreateArgs>(args: Prisma.SelectSubset<T, RoastProfileCreateArgs<ExtArgs>>): Prisma.Prisma__RoastProfileClient<runtime.Types.Result.GetResult<Prisma.$RoastProfilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RoastProfiles.
   * @param {RoastProfileCreateManyArgs} args - Arguments to create many RoastProfiles.
   * @example
   * // Create many RoastProfiles
   * const roastProfile = await prisma.roastProfile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RoastProfileCreateManyArgs>(args?: Prisma.SelectSubset<T, RoastProfileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RoastProfiles and returns the data saved in the database.
   * @param {RoastProfileCreateManyAndReturnArgs} args - Arguments to create many RoastProfiles.
   * @example
   * // Create many RoastProfiles
   * const roastProfile = await prisma.roastProfile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RoastProfiles and only return the `id`
   * const roastProfileWithIdOnly = await prisma.roastProfile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RoastProfileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RoastProfileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoastProfilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RoastProfile.
   * @param {RoastProfileDeleteArgs} args - Arguments to delete one RoastProfile.
   * @example
   * // Delete one RoastProfile
   * const RoastProfile = await prisma.roastProfile.delete({
   *   where: {
   *     // ... filter to delete one RoastProfile
   *   }
   * })
   * 
   */
  delete<T extends RoastProfileDeleteArgs>(args: Prisma.SelectSubset<T, RoastProfileDeleteArgs<ExtArgs>>): Prisma.Prisma__RoastProfileClient<runtime.Types.Result.GetResult<Prisma.$RoastProfilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RoastProfile.
   * @param {RoastProfileUpdateArgs} args - Arguments to update one RoastProfile.
   * @example
   * // Update one RoastProfile
   * const roastProfile = await prisma.roastProfile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RoastProfileUpdateArgs>(args: Prisma.SelectSubset<T, RoastProfileUpdateArgs<ExtArgs>>): Prisma.Prisma__RoastProfileClient<runtime.Types.Result.GetResult<Prisma.$RoastProfilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RoastProfiles.
   * @param {RoastProfileDeleteManyArgs} args - Arguments to filter RoastProfiles to delete.
   * @example
   * // Delete a few RoastProfiles
   * const { count } = await prisma.roastProfile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RoastProfileDeleteManyArgs>(args?: Prisma.SelectSubset<T, RoastProfileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RoastProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoastProfileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RoastProfiles
   * const roastProfile = await prisma.roastProfile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RoastProfileUpdateManyArgs>(args: Prisma.SelectSubset<T, RoastProfileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RoastProfiles and returns the data updated in the database.
   * @param {RoastProfileUpdateManyAndReturnArgs} args - Arguments to update many RoastProfiles.
   * @example
   * // Update many RoastProfiles
   * const roastProfile = await prisma.roastProfile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RoastProfiles and only return the `id`
   * const roastProfileWithIdOnly = await prisma.roastProfile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RoastProfileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RoastProfileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoastProfilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RoastProfile.
   * @param {RoastProfileUpsertArgs} args - Arguments to update or create a RoastProfile.
   * @example
   * // Update or create a RoastProfile
   * const roastProfile = await prisma.roastProfile.upsert({
   *   create: {
   *     // ... data to create a RoastProfile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RoastProfile we want to update
   *   }
   * })
   */
  upsert<T extends RoastProfileUpsertArgs>(args: Prisma.SelectSubset<T, RoastProfileUpsertArgs<ExtArgs>>): Prisma.Prisma__RoastProfileClient<runtime.Types.Result.GetResult<Prisma.$RoastProfilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RoastProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoastProfileCountArgs} args - Arguments to filter RoastProfiles to count.
   * @example
   * // Count the number of RoastProfiles
   * const count = await prisma.roastProfile.count({
   *   where: {
   *     // ... the filter for the RoastProfiles we want to count
   *   }
   * })
  **/
  count<T extends RoastProfileCountArgs>(
    args?: Prisma.Subset<T, RoastProfileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RoastProfileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RoastProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoastProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RoastProfileAggregateArgs>(args: Prisma.Subset<T, RoastProfileAggregateArgs>): Prisma.PrismaPromise<GetRoastProfileAggregateType<T>>

  /**
   * Group by RoastProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RoastProfileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RoastProfileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RoastProfileGroupByArgs['orderBy'] }
      : { orderBy?: RoastProfileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RoastProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRoastProfileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RoastProfile model
 */
readonly fields: RoastProfileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RoastProfile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RoastProfileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  inventoryItem<T extends Prisma.RoastProfile$inventoryItemArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoastProfile$inventoryItemArgs<ExtArgs>>): Prisma.Prisma__InventoryItemClient<runtime.Types.Result.GetResult<Prisma.$InventoryItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RoastProfile model
 */
export interface RoastProfileFieldRefs {
  readonly id: Prisma.FieldRef<"RoastProfile", 'String'>
  readonly batchId: Prisma.FieldRef<"RoastProfile", 'String'>
  readonly date: Prisma.FieldRef<"RoastProfile", 'DateTime'>
  readonly beanType: Prisma.FieldRef<"RoastProfile", 'String'>
  readonly weightIn: Prisma.FieldRef<"RoastProfile", 'Float'>
  readonly weightOut: Prisma.FieldRef<"RoastProfile", 'Float'>
  readonly weightLossPct: Prisma.FieldRef<"RoastProfile", 'Float'>
  readonly totalRoastTime: Prisma.FieldRef<"RoastProfile", 'Int'>
  readonly developmentTime: Prisma.FieldRef<"RoastProfile", 'Int'>
  readonly devTimeRatio: Prisma.FieldRef<"RoastProfile", 'Float'>
  readonly roastCurveData: Prisma.FieldRef<"RoastProfile", 'Json'>
  readonly notes: Prisma.FieldRef<"RoastProfile", 'String'>
  readonly inventoryItemId: Prisma.FieldRef<"RoastProfile", 'String'>
}
    

// Custom InputTypes
/**
 * RoastProfile findUnique
 */
export type RoastProfileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoastProfile
   */
  select?: Prisma.RoastProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoastProfile
   */
  omit?: Prisma.RoastProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoastProfileInclude<ExtArgs> | null
  /**
   * Filter, which RoastProfile to fetch.
   */
  where: Prisma.RoastProfileWhereUniqueInput
}

/**
 * RoastProfile findUniqueOrThrow
 */
export type RoastProfileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoastProfile
   */
  select?: Prisma.RoastProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoastProfile
   */
  omit?: Prisma.RoastProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoastProfileInclude<ExtArgs> | null
  /**
   * Filter, which RoastProfile to fetch.
   */
  where: Prisma.RoastProfileWhereUniqueInput
}

/**
 * RoastProfile findFirst
 */
export type RoastProfileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoastProfile
   */
  select?: Prisma.RoastProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoastProfile
   */
  omit?: Prisma.RoastProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoastProfileInclude<ExtArgs> | null
  /**
   * Filter, which RoastProfile to fetch.
   */
  where?: Prisma.RoastProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoastProfiles to fetch.
   */
  orderBy?: Prisma.RoastProfileOrderByWithRelationInput | Prisma.RoastProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RoastProfiles.
   */
  cursor?: Prisma.RoastProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoastProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoastProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RoastProfiles.
   */
  distinct?: Prisma.RoastProfileScalarFieldEnum | Prisma.RoastProfileScalarFieldEnum[]
}

/**
 * RoastProfile findFirstOrThrow
 */
export type RoastProfileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoastProfile
   */
  select?: Prisma.RoastProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoastProfile
   */
  omit?: Prisma.RoastProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoastProfileInclude<ExtArgs> | null
  /**
   * Filter, which RoastProfile to fetch.
   */
  where?: Prisma.RoastProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoastProfiles to fetch.
   */
  orderBy?: Prisma.RoastProfileOrderByWithRelationInput | Prisma.RoastProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RoastProfiles.
   */
  cursor?: Prisma.RoastProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoastProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoastProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RoastProfiles.
   */
  distinct?: Prisma.RoastProfileScalarFieldEnum | Prisma.RoastProfileScalarFieldEnum[]
}

/**
 * RoastProfile findMany
 */
export type RoastProfileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoastProfile
   */
  select?: Prisma.RoastProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoastProfile
   */
  omit?: Prisma.RoastProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoastProfileInclude<ExtArgs> | null
  /**
   * Filter, which RoastProfiles to fetch.
   */
  where?: Prisma.RoastProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RoastProfiles to fetch.
   */
  orderBy?: Prisma.RoastProfileOrderByWithRelationInput | Prisma.RoastProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RoastProfiles.
   */
  cursor?: Prisma.RoastProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RoastProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RoastProfiles.
   */
  skip?: number
  distinct?: Prisma.RoastProfileScalarFieldEnum | Prisma.RoastProfileScalarFieldEnum[]
}

/**
 * RoastProfile create
 */
export type RoastProfileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoastProfile
   */
  select?: Prisma.RoastProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoastProfile
   */
  omit?: Prisma.RoastProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoastProfileInclude<ExtArgs> | null
  /**
   * The data needed to create a RoastProfile.
   */
  data: Prisma.XOR<Prisma.RoastProfileCreateInput, Prisma.RoastProfileUncheckedCreateInput>
}

/**
 * RoastProfile createMany
 */
export type RoastProfileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RoastProfiles.
   */
  data: Prisma.RoastProfileCreateManyInput | Prisma.RoastProfileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RoastProfile createManyAndReturn
 */
export type RoastProfileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoastProfile
   */
  select?: Prisma.RoastProfileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RoastProfile
   */
  omit?: Prisma.RoastProfileOmit<ExtArgs> | null
  /**
   * The data used to create many RoastProfiles.
   */
  data: Prisma.RoastProfileCreateManyInput | Prisma.RoastProfileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoastProfileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RoastProfile update
 */
export type RoastProfileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoastProfile
   */
  select?: Prisma.RoastProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoastProfile
   */
  omit?: Prisma.RoastProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoastProfileInclude<ExtArgs> | null
  /**
   * The data needed to update a RoastProfile.
   */
  data: Prisma.XOR<Prisma.RoastProfileUpdateInput, Prisma.RoastProfileUncheckedUpdateInput>
  /**
   * Choose, which RoastProfile to update.
   */
  where: Prisma.RoastProfileWhereUniqueInput
}

/**
 * RoastProfile updateMany
 */
export type RoastProfileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RoastProfiles.
   */
  data: Prisma.XOR<Prisma.RoastProfileUpdateManyMutationInput, Prisma.RoastProfileUncheckedUpdateManyInput>
  /**
   * Filter which RoastProfiles to update
   */
  where?: Prisma.RoastProfileWhereInput
  /**
   * Limit how many RoastProfiles to update.
   */
  limit?: number
}

/**
 * RoastProfile updateManyAndReturn
 */
export type RoastProfileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoastProfile
   */
  select?: Prisma.RoastProfileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RoastProfile
   */
  omit?: Prisma.RoastProfileOmit<ExtArgs> | null
  /**
   * The data used to update RoastProfiles.
   */
  data: Prisma.XOR<Prisma.RoastProfileUpdateManyMutationInput, Prisma.RoastProfileUncheckedUpdateManyInput>
  /**
   * Filter which RoastProfiles to update
   */
  where?: Prisma.RoastProfileWhereInput
  /**
   * Limit how many RoastProfiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoastProfileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RoastProfile upsert
 */
export type RoastProfileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoastProfile
   */
  select?: Prisma.RoastProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoastProfile
   */
  omit?: Prisma.RoastProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoastProfileInclude<ExtArgs> | null
  /**
   * The filter to search for the RoastProfile to update in case it exists.
   */
  where: Prisma.RoastProfileWhereUniqueInput
  /**
   * In case the RoastProfile found by the `where` argument doesn't exist, create a new RoastProfile with this data.
   */
  create: Prisma.XOR<Prisma.RoastProfileCreateInput, Prisma.RoastProfileUncheckedCreateInput>
  /**
   * In case the RoastProfile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RoastProfileUpdateInput, Prisma.RoastProfileUncheckedUpdateInput>
}

/**
 * RoastProfile delete
 */
export type RoastProfileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoastProfile
   */
  select?: Prisma.RoastProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoastProfile
   */
  omit?: Prisma.RoastProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoastProfileInclude<ExtArgs> | null
  /**
   * Filter which RoastProfile to delete.
   */
  where: Prisma.RoastProfileWhereUniqueInput
}

/**
 * RoastProfile deleteMany
 */
export type RoastProfileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RoastProfiles to delete
   */
  where?: Prisma.RoastProfileWhereInput
  /**
   * Limit how many RoastProfiles to delete.
   */
  limit?: number
}

/**
 * RoastProfile.inventoryItem
 */
export type RoastProfile$inventoryItemArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InventoryItem
   */
  select?: Prisma.InventoryItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InventoryItem
   */
  omit?: Prisma.InventoryItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InventoryItemInclude<ExtArgs> | null
  where?: Prisma.InventoryItemWhereInput
}

/**
 * RoastProfile without action
 */
export type RoastProfileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RoastProfile
   */
  select?: Prisma.RoastProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RoastProfile
   */
  omit?: Prisma.RoastProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoastProfileInclude<ExtArgs> | null
}
