"use client";

// ENRICHED DATA with 20+ Coffees, Images, and Pairing Logic
export const COFFEE_DATA = [
  // --- AFRICA ---
  {
    id: 'ethiopia-sidamo',
    name: 'Ethiopia Sidamo',
    origin: 'Ethiopia',
    region: 'Sidama',
    producer: 'Taferi Kela',
    process: 'Washed',
    altitude: '2100m',
    price_250g: 16.00,
    aroma: 9, body: 5, acidity: 9, sweetness: 8, aftertaste: 8,
    tags: ['Peach 🍑', 'Mint 🌿', 'Floral 🌸'],
    quality: 'Specialty',
    flavorEmoji: '🍑',
    image: 'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe?auto=format&fit=crop&q=80&w=800',
    description: 'A classic washed Ethiopian profile. Tea-like body with distinct notes of peach and jasmine. High acidity makes it a perfect brightener for any blend.',
    pairings: ['brazil-santos', 'colombia-supremo']
  },
  {
    id: 'kenya-aa',
    name: 'Kenya AA Plus',
    origin: 'Kenya',
    region: 'Nyeri',
    producer: 'Various Smallholders',
    process: 'Washed',
    altitude: '1800m',
    price_250g: 19.50,
    aroma: 9, body: 7, acidity: 10, sweetness: 8, aftertaste: 9,
    tags: ['Blackcurrant 🍇', 'Tomato 🍅', 'Bright ☀️'],
    quality: 'Premium',
    flavorEmoji: '🍇',
    image: 'https://images.unsplash.com/photo-1559525839-b184a4d698c7?auto=format&fit=crop&q=80&w=800',
    description: 'Punchy and vibrant. The famous Kenyan acidity shines through with deep berry sweetness.',
    pairings: ['indonesia-sumatra', 'brazil-cerrado']
  },
  {
    id: 'rwanda-kamwangi',
    name: 'Rwanda Kamwangi',
    origin: 'Rwanda',
    region: 'Kirinyaga',
    producer: 'Kamwangi Factory',
    process: 'Washed',
    altitude: '1700m',
    price_250g: 17.00,
    aroma: 8, body: 6, acidity: 8, sweetness: 9, aftertaste: 8,
    tags: ['Orange 🍊', 'Brown Sugar 🤎', 'Silky 🧣'],
    quality: 'Specialty',
    flavorEmoji: '🍊',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800',
    description: 'Complex and sweet. Acts as a great bridge between bright acids and heavy bodies.',
    pairings: ['colombia-huila']
  },
  {
    id: 'burundi-fug',
    name: 'Burundi Fully Washed',
    origin: 'Burundi',
    region: 'Kayanza',
    producer: 'Heza Station',
    process: 'Washed',
    altitude: '1900m',
    price_250g: 15.50,
    aroma: 7, body: 7, acidity: 8, sweetness: 7, aftertaste: 7,
    tags: ['Fig 🟣', 'Honey 🍯', 'Tea 🍵'],
    quality: 'Specialty',
    flavorEmoji: '🟣',
    image: 'https://images.unsplash.com/photo-1610632380989-680fe40816c6?auto=format&fit=crop&q=80&w=800',
    description: 'A hidden gem. Very sweet with a syrupy body that holds up well in espresso.',
    pairings: ['brazil-santos']
  },

  // --- SOUTH AMERICA ---
  {
    id: 'colombia-el-paraiso-rose',
    name: 'Colombia El Paraiso (Rose)',
    origin: 'Colombia',
    region: 'Cauca',
    producer: 'Diego Bermudez',
    process: 'Double Anaerobic',
    altitude: '1930m',
    price_250g: 22.00,
    aroma: 10, body: 5, acidity: 8, sweetness: 10, aftertaste: 9,
    tags: ['Rose 🌹', 'Strawberry 🍓', 'Yogurt 🍦'],
    quality: 'Competition',
    flavorEmoji: '🌹',
    image: 'https://images.unsplash.com/photo-1621267860478-dbdd5e82196d?auto=format&fit=crop&q=80&w=800',
    description: 'An experimental microlot that tastes distinctly of roses and strawberry yogurt. Use sparingly to add an exotic twist.',
    pairings: ['brazil-sul-de-minas']
  },
  {
    id: 'colombia-supremo',
    name: 'Colombia Supremo',
    origin: 'Colombia',
    region: 'Huila',
    producer: 'Various',
    process: 'Washed',
    altitude: '1600m',
    price_250g: 14.00,
    aroma: 7, body: 7, acidity: 6, sweetness: 8, aftertaste: 7,
    tags: ['Caramel 🍬', 'Nutty 🥜', 'Balanced ⚖️'],
    quality: 'Premium Commercial',
    flavorEmoji: '🍬',
    image: 'https://images.unsplash.com/photo-1552346988-5f9922a468d9?auto=format&fit=crop&q=80&w=800',
    description: 'The reliable workhorse. Perfectly balanced with notes of caramel and nuts. Ideal base for any house blend.',
    pairings: ['ethiopia-sidamo', 'guatemala-antigua']
  },
  {
    id: 'brazil-sul-de-minas',
    name: 'Brazil Sul de Minas',
    origin: 'Brazil',
    region: 'Minas Gerais',
    producer: 'Cocatrel',
    process: 'Natural',
    altitude: '1100m',
    price_250g: 12.00,
    aroma: 5, body: 9, acidity: 4, sweetness: 8, aftertaste: 6,
    tags: ['Chocolate 🍫', 'Hazelnut 🌰', 'Low Acid 📉'],
    quality: 'Commercial',
    flavorEmoji: '🍫',
    image: 'https://images.unsplash.com/photo-1518832553480-cd0e625ed3e6?auto=format&fit=crop&q=80&w=800',
    description: 'Classic Brazil. Huge chocolate body, low acidity. The perfect foundation for espresso blends.',
    pairings: ['ethiopia-sidamo', 'colombia-supremo']
  },
  {
    id: 'brazil-cerrado',
    name: 'Brazil Cerrado',
    origin: 'Brazil',
    region: 'Cerrado Mineiro',
    producer: 'Daterra',
    process: 'Natural',
    altitude: '1200m',
    price_250g: 13.50,
    aroma: 6, body: 8, acidity: 4, sweetness: 9, aftertaste: 7,
    tags: ['Toffee 🍮', 'Walnut 🥜', 'Smooth 🧈'],
    quality: 'Premium',
    flavorEmoji: '🍮',
    image: 'https://images.unsplash.com/photo-1589533610925-1cffc30d677c?auto=format&fit=crop&q=80&w=800',
    description: 'Sweet and consistent. A step up from standard Santos with cleaner sweetness.',
    pairings: ['costa-rica-shb']
  },
  {
    id: 'peru-organic',
    name: 'Peru Norte Organic',
    origin: 'Peru',
    region: 'Cajamarca',
    producer: 'Cenfrocafe',
    process: 'Washed',
    altitude: '1750m',
    price_250g: 15.00,
    aroma: 7, body: 6, acidity: 6, sweetness: 7, aftertaste: 6,
    tags: ['Almond 🥜', 'Vanilla 🍦', 'Mild ☁️'],
    quality: 'Organic',
    flavorEmoji: '🍦',
    image: 'https://images.unsplash.com/photo-1524350876685-274059332603?auto=format&fit=crop&q=80&w=800',
    description: 'Gentle and organic. A crowd-pleaser that adds sweetness without overpowering.',
    pairings: ['honduras-shg']
  },

  // --- CENTRAL AMERICA ---
  {
    id: 'guatemala-el-socorro',
    name: 'Guatemala El Socorro',
    origin: 'Guatemala',
    region: 'Palencia',
    producer: 'Juan Diego',
    process: 'Washed',
    altitude: '1850m',
    price_250g: 18.00,
    aroma: 8, body: 6, acidity: 7, sweetness: 9, aftertaste: 7,
    tags: ['Apple 🍎', 'Honey 🍯', 'Complex 🧩'],
    quality: 'Exceptional',
    flavorEmoji: '🍯',
    image: 'https://images.unsplash.com/photo-1511537632536-34a72e58c18e?auto=format&fit=crop&q=80&w=800',
    description: 'Award-winning farm. A pristine cup with crisp apple acidity and lingering honey sweetness.',
    pairings: ['el-salvador-santa-ana']
  },
  {
    id: 'el-salvador-santa-ana',
    name: 'El Salvador Santa Ana',
    origin: 'El Salvador',
    region: 'Apaneca',
    producer: 'El Borbollon',
    process: 'Natural',
    altitude: '1400m',
    price_250g: 14.50,
    aroma: 6, body: 8, acidity: 5, sweetness: 9, aftertaste: 7,
    tags: ['Orange 🍊', 'Chocolate 🍫', 'Creamy 🥛'],
    quality: 'Specialty',
    flavorEmoji: '🍊',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&q=80&w=800',
    description: 'Like a chocolate orange bar. Natural processing adds a fruity layer to the classic chocolate base.',
    pairings: ['guatemala-antigua']
  },
  {
    id: 'costa-rica-shb',
    name: 'Costa Rica Tarrazu',
    origin: 'Costa Rica',
    region: 'Tarrazu',
    producer: 'Coopeota',
    process: 'Honey',
    altitude: '1600m',
    price_250g: 16.50,
    aroma: 8, body: 6, acidity: 7, sweetness: 9, aftertaste: 8,
    tags: ['Maple 🍁', 'Apricot 🍑', 'Clean ✨'],
    quality: 'Specialty',
    flavorEmoji: '🍁',
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&q=80&w=800',
    description: 'Honey processed for extra body and sweetness. Very clean cup with stone fruit notes.',
    pairings: ['brazil-cerrado']
  },
  {
    id: 'nicaragua-decaf',
    name: 'Nicaragua Decaf',
    origin: 'Nicaragua',
    region: 'Jinotega',
    producer: 'Various',
    process: 'Sugar Cane',
    altitude: '1200m',
    price_250g: 15.00,
    aroma: 6, body: 6, acidity: 4, sweetness: 9, aftertaste: 5,
    tags: ['Malt 🌾', 'Sweet 🍬', 'Decaf 💤'],
    quality: 'Decaf',
    flavorEmoji: '🌾',
    image: 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?auto=format&fit=crop&q=80&w=800',
    description: 'Chemical-free decaf using sugar cane ethanol. Retains flavor and sweetness surprisingly well.',
    pairings: ['brazil-santos'] // For half-caf blends
  },
  {
    id: 'honduras-shg',
    name: 'Honduras Capucas',
    origin: 'Honduras',
    region: 'Copan',
    producer: 'COCAFCAL',
    process: 'Washed',
    altitude: '1450m',
    price_250g: 13.50,
    aroma: 6, body: 7, acidity: 6, sweetness: 7, aftertaste: 6,
    tags: ['Cocoa 🍫', 'Tobacco 🍂', 'Solid 🧱'],
    quality: 'Organic',
    flavorEmoji: '🍂',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=800',
    description: 'Earthy and grounded. A great component to add depth and bass notes to a blend.',
    pairings: ['ethiopia-sidamo']
  },

  // --- ASIA / PACIFIC ---
  {
    id: 'indonesia-sumatra',
    name: 'Sumatra Mandheling',
    origin: 'Indonesia',
    region: 'Aceh',
    producer: 'Smallholders',
    process: 'Wet Hull',
    altitude: '1300m',
    price_250g: 16.00,
    aroma: 6, body: 10, acidity: 3, sweetness: 6, aftertaste: 9,
    tags: ['Earth 🌍', 'Spice 🌶️', 'Heavy 🏋️'],
    quality: 'Grade 1',
    flavorEmoji: '🌶️',
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&q=80&w=800',
    description: 'Massive body and low acidity. Spicy, earthy, and intense. Use to add weight/crema to espresso.',
    pairings: ['ethiopia-sidamo', 'brazil-santos'] // Mocha Java style
  },
  {
    id: 'vietnam-java',
    name: 'Vietnam Arabica',
    origin: 'Vietnam',
    region: 'Da Lat',
    producer: 'Various',
    process: 'Washed',
    altitude: '1500m',
    price_250g: 13.00,
    aroma: 5, body: 8, acidity: 4, sweetness: 7, aftertaste: 6,
    tags: ['Nutty 🥜', 'Woody 🪵', 'Bold 🎸'],
    quality: 'Premium',
    flavorEmoji: '🪵',
    image: 'https://images.unsplash.com/photo-1596043237237-774226736277?auto=format&fit=crop&q=80&w=800',
    description: 'Clean Vietnamese Arabica. Chocolaty and nutty, less earthy than Sumatra.',
    pairings: ['colombia-supremo']
  },
  {
    id: 'papua-new-guinea',
    name: 'PNG Sigri',
    origin: 'Papua New Guinea',
    region: 'Waghi Valley',
    producer: 'Sigri Estate',
    process: 'Washed',
    altitude: '1600m',
    price_250g: 17.50,
    aroma: 8, body: 7, acidity: 7, sweetness: 8, aftertaste: 8,
    tags: ['Mango 🥭', 'Spice 🌶️', 'Complex 🌀'],
    quality: 'Specialty',
    flavorEmoji: '🥭',
    image: 'https://images.unsplash.com/photo-1559525839-4f34620a6727?auto=format&fit=crop&q=80&w=800',
    description: 'Unique profile often compared to Jamaica Blue Mountain. Sweet, fruity, and spicy.',
    pairings: ['brazil-cerrado']
  },
  {
    id: 'india-monsooned',
    name: 'India Monsooned Malabar',
    origin: 'India',
    region: 'Malabar Coast',
    producer: 'Various',
    process: 'Monsooned',
    altitude: '1100m',
    price_250g: 15.50,
    aroma: 5, body: 9, acidity: 2, sweetness: 6, aftertaste: 7,
    tags: ['Straw 🌾', 'Musty 🏛️', 'Mellow 😌'],
    quality: 'Specialty AA',
    flavorEmoji: '🌾',
    image: 'https://images.unsplash.com/photo-1613336026275-d6d473084e85?auto=format&fit=crop&q=80&w=800',
    description: 'Exposed to monsoon winds to swell the beans. Results in zero acidity and heavy, mellow body.',
    pairings: ['ethiopia-sidamo']
  }
];

// MOCK BLEND TEMPLATES
export const BLEND_TEMPLATES = [
    {
        id: 'morning-glory',
        name: 'Morning Glory',
        description: 'Bright and punchy breakfast blend.',
        price: 15.50,
        components: [
            { id: 'colombia-supremo', percentage: 60 },
            { id: 'ethiopia-sidamo', percentage: 40 }
        ]
    },
    {
        id: 'espresso-punch',
        name: 'Espresso Punch',
        description: 'Traditional Italian style with heavy body.',
        price: 13.50,
        components: [
            { id: 'brazil-sul-de-minas', percentage: 50 },
            { id: 'colombia-supremo', percentage: 30 },
            { id: 'indonesia-sumatra', percentage: 20 }
        ]
    },
    {
        id: 'fruit-bomb',
        name: 'Fruit Bomb',
        description: 'Wild, fruity, and sweet. Not for the faint hearted.',
        price: 19.00,
        components: [
            { id: 'colombia-el-paraiso-rose', percentage: 40 },
            { id: 'kenya-aa', percentage: 60 }
        ]
    }
];
